"""
Report Integrity Verification Script.

Validates that PDF/Excel reports generated by report_service are mathematically
identical to the Dashboard metrics from metrics_service (single source of truth).

Usage:
    # Against local dev server:
    python -m tests.test_report_integrity

    # Against custom URL:
    INVESTAI_API_URL=https://app.example.com/api/v1 python -m tests.test_report_integrity

Requires INVESTAI_TOKEN or (INVESTAI_EMAIL + INVESTAI_PASSWORD).
"""

import io
import os
import sys

import httpx

API_URL = os.getenv("INVESTAI_API_URL", "http://localhost:8000/api/v1")
TOKEN = os.getenv("INVESTAI_TOKEN", "")
EMAIL = os.getenv("INVESTAI_EMAIL", "")
PASSWORD = os.getenv("INVESTAI_PASSWORD", "")

ABS_TOL = 0.02  # 0.02 EUR


def approx_eq(a: float, b: float, atol: float = ABS_TOL) -> bool:
    if a is None or b is None:
        return a is None and b is None
    return abs(a - b) <= atol


class ReportIntegrityVerifier:
    """Verifies that report exports match Dashboard data exactly."""

    def __init__(self, dashboard: dict, excel_bytes: bytes, pdf_bytes: bytes):
        self.d = dashboard
        self.adv = dashboard.get("advanced_metrics", {})
        self.pnl = self.adv.get("pnl_breakdown", {})
        self.risk = self.adv.get("risk_metrics", {})
        self.conc = self.adv.get("concentration", {})
        self.stress = self.adv.get("stress_tests", [])
        self.excel_bytes = excel_bytes
        self.pdf_bytes = pdf_bytes
        self.passes: list[str] = []
        self.errors: list[str] = []

    def _check(self, name: str, condition: bool, detail: str = ""):
        if condition:
            self.passes.append(f"  PASS  {name}")
        else:
            msg = f"  FAIL  {name}"
            if detail:
                msg += f" -- {detail}"
            self.errors.append(msg)

    def run_all(self) -> bool:
        """Run all integrity checks."""
        self.check_pdf_generated()
        self.check_excel_generated()
        self.check_excel_summary_sheet()
        self.check_excel_pnl_breakdown()
        self.check_excel_risk_sheet()
        self.check_excel_risk_metrics()
        self.check_excel_platform_sheet()
        self.check_excel_assets_columns()
        self.check_pnl_net_consistency()

        print("\n" + "=" * 60)
        print("REPORT INTEGRITY VERIFICATION RESULTS")
        print("=" * 60)
        for p in self.passes:
            print(p)
        for e in self.errors:
            print(e)
        print("-" * 60)
        print(f"  {len(self.passes)} tests passés, {len(self.errors)} échecs")
        print("=" * 60)

        return len(self.errors) == 0

    # ── PDF checks ───────────────────────────────────────────────

    def check_pdf_generated(self):
        """PDF should be non-empty and start with PDF header."""
        self._check(
            "R1: PDF généré (non-vide)",
            len(self.pdf_bytes) > 100,
            f"pdf_size={len(self.pdf_bytes)} bytes",
        )
        self._check(
            "R1b: PDF header valide",
            self.pdf_bytes[:5] == b"%PDF-",
            f"header={self.pdf_bytes[:10]}",
        )

    # ── Excel checks ─────────────────────────────────────────────

    def _load_workbook(self):
        from openpyxl import load_workbook

        return load_workbook(io.BytesIO(self.excel_bytes), data_only=True)

    def check_excel_generated(self):
        """Excel should be non-empty and loadable."""
        self._check(
            "R2: Excel généré (non-vide)",
            len(self.excel_bytes) > 100,
            f"xlsx_size={len(self.excel_bytes)} bytes",
        )
        try:
            wb = self._load_workbook()
            self._check("R2b: Excel chargeable", True)
            wb.close()
        except Exception as e:
            self._check("R2b: Excel chargeable", False, str(e))

    def check_excel_summary_sheet(self):
        """Résumé sheet: total_value and total_invested match Dashboard."""
        try:
            wb = self._load_workbook()
            ws = wb["Résumé"]

            # Find values — summary starts at row 5
            values = {}
            for row in range(5, 20):
                label = ws[f"A{row}"].value
                val = ws[f"B{row}"].value
                if label:
                    values[label] = val

            expected_value = self.d["total_value"]
            actual_value = values.get("Valeur totale", 0)
            self._check(
                "R3: Excel Valeur totale = Dashboard",
                approx_eq(actual_value, expected_value),
                f"excel={actual_value}, dashboard={expected_value:.2f}",
            )

            expected_invested = self.d["total_invested"]
            actual_invested = values.get("Total investi", 0)
            self._check(
                "R3b: Excel Total investi = Dashboard",
                approx_eq(actual_invested, expected_invested),
                f"excel={actual_invested}, dashboard={expected_invested:.2f}",
            )
            wb.close()
        except Exception as e:
            self._check("R3: Excel Résumé sheet", False, str(e))

    def check_excel_pnl_breakdown(self):
        """Résumé sheet: P&L breakdown matches Dashboard pnl_breakdown."""
        try:
            wb = self._load_workbook()
            ws = wb["Résumé"]

            values = {}
            for row in range(5, 25):
                label = ws[f"A{row}"].value
                val = ws[f"B{row}"].value
                if label:
                    values[label] = val

            # P&L Latent
            expected = self.pnl.get("unrealized_pnl", 0)
            actual = values.get("P&L Latent")
            self._check(
                "R4: Excel P&L Latent = Dashboard",
                actual is not None and approx_eq(actual, expected),
                f"excel={actual}, dashboard={expected:.2f}",
            )

            # P&L Réalisé
            expected = self.pnl.get("realized_pnl", 0)
            actual = values.get("P&L Réalisé")
            self._check(
                "R4b: Excel P&L Réalisé = Dashboard",
                actual is not None and approx_eq(actual, expected),
                f"excel={actual}, dashboard={expected:.2f}",
            )

            # Total Frais
            expected = self.pnl.get("total_fees", 0)
            actual = values.get("Total Frais")
            self._check(
                "R4c: Excel Total Frais = Dashboard",
                actual is not None and approx_eq(actual, expected),
                f"excel={actual}, dashboard={expected:.2f}",
            )

            # P&L Net
            expected = self.pnl.get("net_pnl", 0)
            actual = values.get("P&L Net")
            self._check(
                "R4d: Excel P&L Net = Dashboard",
                actual is not None and approx_eq(actual, expected),
                f"excel={actual}, dashboard={expected:.2f}",
            )

            wb.close()
        except Exception as e:
            self._check("R4: Excel P&L breakdown", False, str(e))

    def check_excel_risk_sheet(self):
        """Analyse de Risque sheet exists and has 6+ metrics."""
        try:
            wb = self._load_workbook()
            self._check(
                "R5: Onglet 'Analyse de Risque' présent",
                "Analyse de Risque" in wb.sheetnames,
                f"sheets={wb.sheetnames}",
            )

            if "Analyse de Risque" in wb.sheetnames:
                ws = wb["Analyse de Risque"]
                # Count non-empty label rows (exclude header and separator rows)
                labels = []
                for row in range(2, 25):
                    label = ws[f"A{row}"].value
                    if label and label.strip():
                        labels.append(label)
                self._check(
                    "R5b: Onglet Risque contient >= 6 métriques",
                    len(labels) >= 6,
                    f"found {len(labels)} metrics: {labels[:6]}",
                )

                # Check specific expected labels
                expected_labels = [
                    "Volatilité annualisée",
                    "Ratio de Sharpe",
                    "Max Drawdown",
                    "Indice HHI",
                    "Stress Test -20%",
                    "Stress Test -40%",
                ]
                for exp in expected_labels:
                    found = any(exp in lbl for lbl in labels)
                    self._check(
                        f"R5c: Risque contient '{exp}'",
                        found,
                        f"labels={labels}",
                    )
            wb.close()
        except Exception as e:
            self._check("R5: Excel Analyse de Risque", False, str(e))

    def check_excel_risk_metrics(self):
        """Analyse de Risque sheet: HHI and VaR match Dashboard."""
        try:
            wb = self._load_workbook()
            if "Analyse de Risque" not in wb.sheetnames:
                self._check("R6: Risque metrics match", False, "sheet missing")
                return

            ws = wb["Analyse de Risque"]
            values = {}
            for row in range(2, 25):
                label = ws[f"A{row}"].value
                val = ws[f"B{row}"].value
                if label:
                    values[label] = val

            # HHI
            expected_hhi = self.conc.get("hhi", 0)
            actual_hhi = values.get("Indice HHI", 0)
            self._check(
                "R6: Excel HHI = Dashboard",
                approx_eq(float(actual_hhi or 0), expected_hhi, atol=1.0),
                f"excel={actual_hhi}, dashboard={expected_hhi:.0f}",
            )

            # VaR 95% amount
            expected_var = self.risk.get("var_95", {}).get("var_amount", 0)
            actual_var = values.get("VaR 95% (montant)", 0)
            self._check(
                "R6b: Excel VaR 95% = Dashboard",
                approx_eq(float(actual_var or 0), expected_var, atol=1.0),
                f"excel={actual_var}, dashboard={expected_var:.2f}",
            )

            wb.close()
        except Exception as e:
            self._check("R6: Excel risk metrics match", False, str(e))

    def check_excel_platform_sheet(self):
        """Perf. par Plateforme sheet exists with correct columns."""
        try:
            wb = self._load_workbook()
            self._check(
                "R7: Onglet 'Perf. par Plateforme' présent",
                "Perf. par Plateforme" in wb.sheetnames,
                f"sheets={wb.sheetnames}",
            )

            if "Perf. par Plateforme" in wb.sheetnames:
                ws = wb["Perf. par Plateforme"]
                # Check header row
                headers = [ws.cell(row=1, column=c).value for c in range(1, 8)]
                expected_cols = ["Plateforme", "Nb Actifs", "Valeur", "Investi", "Frais", "P&L Net", "ROI %"]
                self._check(
                    "R7b: Plateforme colonnes correctes",
                    headers == expected_cols,
                    f"got={headers}, expected={expected_cols}",
                )

                # Check at least 1 data row
                first_platform = ws.cell(row=2, column=1).value
                self._check(
                    "R7c: Plateforme contient des données",
                    first_platform is not None and first_platform != "",
                    f"first_row_col1={first_platform}",
                )

            wb.close()
        except Exception as e:
            self._check("R7: Excel Perf. par Plateforme", False, str(e))

    def check_excel_assets_columns(self):
        """Actifs sheet has Break-even and Risque columns."""
        try:
            wb = self._load_workbook()
            if "Actifs" not in wb.sheetnames:
                self._check("R8: Actifs sheet", False, "sheet missing")
                return

            ws = wb["Actifs"]
            headers = [ws.cell(row=1, column=c).value for c in range(1, 16)]
            headers = [h for h in headers if h is not None]

            self._check(
                "R8: Actifs contient 'Break-even'",
                "Break-even" in headers,
                f"headers={headers}",
            )
            self._check(
                "R8b: Actifs contient 'Risque'",
                "Risque" in headers,
                f"headers={headers}",
            )
            self._check(
                "R8c: Actifs contient 'Plateforme'",
                "Plateforme" in headers,
                f"headers={headers}",
            )
            self._check(
                "R8d: Actifs contient 'Frais'",
                "Frais" in headers,
                f"headers={headers}",
            )

            wb.close()
        except Exception as e:
            self._check("R8: Excel Actifs columns", False, str(e))

    def check_pnl_net_consistency(self):
        """P&L Net from Dashboard must equal net_gain_loss - fees."""
        net_gain_loss = self.d.get("net_gain_loss", 0)
        total_pnl = self.pnl.get("total_pnl", 0)
        net_pnl = self.pnl.get("net_pnl", 0)
        fees = self.pnl.get("total_fees", 0)

        # Verify root formula holds: total_pnl = total_value - total_invested
        expected_pnl = self.d["total_value"] - self.d["total_invested"]
        self._check(
            "R9: total_pnl = total_value - total_invested",
            approx_eq(total_pnl, expected_pnl),
            f"total_pnl={total_pnl:.2f}, expected={expected_pnl:.2f}",
        )

        # net_pnl = total_pnl - fees
        expected_net = total_pnl - fees
        self._check(
            "R9b: net_pnl = total_pnl - fees",
            approx_eq(net_pnl, expected_net),
            f"net_pnl={net_pnl:.2f}, expected={expected_net:.2f}",
        )

        # net_gain_loss matches total_pnl (same root formula)
        self._check(
            "R9c: net_gain_loss = total_pnl (unified root)",
            approx_eq(net_gain_loss, total_pnl),
            f"net_gain_loss={net_gain_loss:.2f}, total_pnl={total_pnl:.2f}",
        )


def get_token() -> str:
    if TOKEN:
        return TOKEN
    if not EMAIL or not PASSWORD:
        print("ERROR: Set INVESTAI_TOKEN or (INVESTAI_EMAIL + INVESTAI_PASSWORD)")
        sys.exit(1)
    r = httpx.post(f"{API_URL}/auth/login", json={"email": EMAIL, "password": PASSWORD})
    r.raise_for_status()
    return r.json()["access_token"]


def main():
    token = get_token()
    headers = {"Authorization": f"Bearer {token}"}

    # 1. Fetch Dashboard (all-time)
    print(f"Fetching dashboard from {API_URL}/dashboard?days=0 ...")
    r = httpx.get(f"{API_URL}/dashboard?days=0", headers=headers, timeout=60)
    r.raise_for_status()
    dashboard = r.json()

    print("\n--- Dashboard Key Values ---")
    print(f"  Patrimoine:    {dashboard['total_value']:.2f} EUR")
    print(f"  Investi:       {dashboard['total_invested']:.2f} EUR")
    print(f"  Net Gain/Loss: {dashboard['net_gain_loss']:.2f} EUR")
    pnl = dashboard.get("advanced_metrics", {}).get("pnl_breakdown", {})
    print(f"  P&L Latent:    {pnl.get('unrealized_pnl', 0):.2f} EUR")
    print(f"  P&L Réalisé:   {pnl.get('realized_pnl', 0):.2f} EUR")
    print(f"  Total Frais:   {pnl.get('total_fees', 0):.2f} EUR")
    print(f"  P&L Net:       {pnl.get('net_pnl', 0):.2f} EUR")
    conc = dashboard.get("advanced_metrics", {}).get("concentration", {})
    print(f"  HHI:           {conc.get('hhi', 0):.0f}")
    risk = dashboard.get("advanced_metrics", {}).get("risk_metrics", {})
    var95 = risk.get("var_95", {})
    print(f"  VaR 95%:       {var95.get('var_amount', 0):.2f} EUR")

    # 2. Generate PDF
    print(f"\nFetching PDF from {API_URL}/reports/performance/pdf ...")
    r = httpx.get(f"{API_URL}/reports/performance/pdf", headers=headers, timeout=120)
    r.raise_for_status()
    pdf_bytes = r.content
    print(f"  PDF size: {len(pdf_bytes):,} bytes")

    # 3. Generate Excel
    print(f"Fetching Excel from {API_URL}/reports/performance/excel ...")
    r = httpx.get(f"{API_URL}/reports/performance/excel", headers=headers, timeout=120)
    r.raise_for_status()
    excel_bytes = r.content
    print(f"  Excel size: {len(excel_bytes):,} bytes")

    # 4. Run verification
    verifier = ReportIntegrityVerifier(dashboard, excel_bytes, pdf_bytes)
    ok = verifier.run_all()

    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
